title: Snowplow Routing in Middleton, Wisconsin
description: An efficient, open-source implementation of the snowplow routing problem
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
